[project]
org-name= "ballerinax"
version= "2.0.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["MongoDB", "NoSQL"]
repository = "https://github.com/ballerina-platform/module-ballerinax-mongodb"

[dependencies]

[platform]
target = "java8"

    [[platform.libraries]]
    module = "mongodb"
    path = "../mongodb-native/target/mongodb-native-2.0.0.jar"
    artafactId = "mongodb-native"
    version = "2.0.0"
    groupId = "org.ballerinalang"
